// src/__tests__/diffFilter.test.ts
// Unit tests for diffFilter — split helpers and filter rules.
// No VS Code host or mocks needed — this module is pure functions.

import { describe, it, expect } from 'vitest';
import { filterDiff, splitDiffByFile, isNewFile, normalizeGitLabDiffResponse, normalizeRemoteDiff } from '../diffFilter';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function makeDiff(...sections: string[]): string {
  return sections.join('\n');
}

function tsSection(name = 'src/foo.ts'): string {
  return `diff --git a/${name} b/${name}
--- a/${name}
+++ b/${name}
@@ -1,3 +1,4 @@
 const x = 1;
+console.log('hello');
 const y = 2;
 const z = 3;`;
}

function lockSection(): string {
  return `diff --git a/package-lock.json b/package-lock.json
--- a/package-lock.json
+++ b/package-lock.json
@@ -1,5 +1,5 @@
 {
-  "version": "1.0.0",
+  "version": "1.0.1",
   "lockfileVersion": 3,
 }`;
}

function yarnLockSection(): string {
  return `diff --git a/yarn.lock b/yarn.lock
--- a/yarn.lock
+++ b/yarn.lock
@@ -1,3 +1,3 @@
-# yarn lockfile v1
+# yarn lockfile v2`;
}

function cargoLockSection(): string {
  return `diff --git a/Cargo.lock b/Cargo.lock
--- a/Cargo.lock
+++ b/Cargo.lock
@@ -1,5 +1,5 @@
 # This file is automatically @generated by Cargo.
 # It is not intended for manual editing.
-version = 3
+version = 4`;
}

function binarySection(): string {
  return `diff --git a/assets/icon.png b/assets/icon.png
Binary files a/assets/icon.png and b/assets/icon.png differ`;
}

function generatedPbSection(): string {
  return `diff --git a/src/generated/user.pb.ts b/src/generated/user.pb.ts
--- a/src/generated/user.pb.ts
+++ b/src/generated/user.pb.ts
@@ -1,3 +1,4 @@
 // Generated by protoc
+const new_field = 1;`;
}

function minifiedSection(): string {
  return `diff --git a/dist/bundle.min.js b/dist/bundle.min.js
--- a/dist/bundle.min.js
+++ b/dist/bundle.min.js
@@ -1 +1 @@
-!function(e){...}
+!function(e){...updated...}`;
}

function changelogSection(): string {
  return `diff --git a/CHANGELOG.md b/CHANGELOG.md
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -1,3 +1,5 @@
 # Changelog
+## 1.0.1
+- Fixed build`;
}

function coverageSection(): string {
  return `diff --git a/coverage/lcov.info b/coverage/lcov.info
--- a/coverage/lcov.info
+++ b/coverage/lcov.info
@@ -1,3 +1,3 @@
-TN:
-SF:src/foo.ts
+TN:updated
+SF:src/foo.ts`;
}

function newFileSection(name = 'src/newModule.ts'): string {
  return `diff --git a/dev/null b/${name}
new file mode 100644
index 0000000..e69de29
--- /dev/null
+++ b/${name}
@@ -0,0 +1,3 @@
+export const foo = 1;
+export const bar = 2;
+export const baz = 3;`;
}

// ---------------------------------------------------------------------------
// Tests — filterDiff
// ---------------------------------------------------------------------------

describe('filterDiff', () => {
  it('returns the full diff when all files are reviewable', () => {
    const diff = makeDiff(tsSection('src/foo.ts'), tsSection('src/bar.ts'));
    const result = filterDiff(diff);

    expect(result.keptFiles).toBe(2);
    expect(result.skippedFiles).toBe(0);
    expect(result.filteredDiff).toContain('src/foo.ts');
    expect(result.filteredDiff).toContain('src/bar.ts');
  });

  it('removes package-lock.json sections', () => {
    const diff = makeDiff(tsSection('src/foo.ts'), lockSection());
    const result = filterDiff(diff);

    expect(result.keptFiles).toBe(1);
    expect(result.skippedFiles).toBe(1);
    expect(result.skippedFilePaths).toContain('package-lock.json');
    expect(result.filteredDiff).not.toContain('package-lock.json');
  });

  it('removes yarn.lock sections', () => {
    const diff = makeDiff(yarnLockSection(), tsSection('src/app.ts'));
    const result = filterDiff(diff);

    expect(result.skippedFiles).toBe(1);
    expect(result.skippedFilePaths).toContain('yarn.lock');
  });

  it('removes Cargo.lock sections', () => {
    const diff = makeDiff(cargoLockSection(), tsSection('src/main.ts'));
    const result = filterDiff(diff);

    expect(result.skippedFiles).toBe(1);
    expect(result.skippedFilePaths).toContain('Cargo.lock');
  });

  it('removes binary file sections', () => {
    const diff = makeDiff(binarySection(), tsSection('src/util.ts'));
    const result = filterDiff(diff);

    expect(result.skippedFiles).toBe(1);
    expect(result.skippedFilePaths).toContain('assets/icon.png');
  });

  it('removes generated protobuf files', () => {
    const diff = makeDiff(generatedPbSection(), tsSection('src/handlers.ts'));
    const result = filterDiff(diff);

    expect(result.skippedFiles).toBe(1);
    expect(result.skippedFilePaths[0]).toContain('user.pb.ts');
  });

  it('removes minified JS files', () => {
    const diff = makeDiff(minifiedSection(), tsSection('src/index.ts'));
    const result = filterDiff(diff);

    expect(result.skippedFiles).toBe(1);
    expect(result.skippedFilePaths[0]).toContain('bundle.min.js');
  });

  it('removes CHANGELOG.md sections', () => {
    const diff = makeDiff(changelogSection(), tsSection('src/app.ts'));
    const result = filterDiff(diff);

    expect(result.skippedFiles).toBe(1);
    expect(result.skippedFilePaths).toContain('CHANGELOG.md');
  });

  it('removes coverage report sections', () => {
    const diff = makeDiff(coverageSection(), tsSection('src/app.ts'));
    const result = filterDiff(diff);

    expect(result.skippedFiles).toBe(1);
    expect(result.skippedFilePaths[0]).toContain('lcov.info');
  });

  it('removes multiple files in a single diff', () => {
    const diff = makeDiff(
      lockSection(),
      tsSection('src/foo.ts'),
      yarnLockSection(),
      binarySection(),
      tsSection('src/bar.ts'),
      generatedPbSection()
    );
    const result = filterDiff(diff);

    expect(result.keptFiles).toBe(2);
    expect(result.skippedFiles).toBe(4);
    expect(result.skippedFilePaths).toContain('package-lock.json');
    expect(result.skippedFilePaths).toContain('yarn.lock');
    expect(result.skippedFilePaths[2]).toContain('icon.png');
    expect(result.skippedFilePaths[3]).toContain('user.pb.ts');
  });

  it('reports estimated token savings', () => {
    const lockContent = lockSection();
    const diff = makeDiff(lockContent, tsSection('src/foo.ts'));
    const result = filterDiff(diff);

    expect(result.estimatedTokensSaved).toBeGreaterThan(0);
    // Rough calculation: ~4 chars per token
    expect(result.estimatedTokensSaved).toBe(Math.round(lockContent.length / 4));
  });

  it('tracks both kept and skipped file paths', () => {
    const diff = makeDiff(
      lockSection(),
      tsSection('src/foo.ts'),
      binarySection(),
      tsSection('src/bar.ts')
    );
    const result = filterDiff(diff);

    expect(result.keptFilePaths).toEqual(['src/foo.ts', 'src/bar.ts']);
    expect(result.skippedFilePaths).toContain('package-lock.json');
    expect(result.skippedFilePaths).toContain('assets/icon.png');
  });

  it('handles empty diff gracefully', () => {
    const result = filterDiff('');

    // Empty string produces one non-matching section that gets kept
    expect(result.keptFiles).toBe(1);
    expect(result.skippedFiles).toBe(0);
    expect(result.filteredDiff.trim()).toBe('');
  });

  it('handles diff with only non-reviewable files', () => {
    const diff = makeDiff(lockSection(), binarySection());
    const result = filterDiff(diff);

    expect(result.keptFiles).toBe(0);
    expect(result.skippedFiles).toBe(2);
    expect(result.filteredDiff.trim()).toBe('');
  });
});

// ---------------------------------------------------------------------------
// Tests — splitDiffByFile
// ---------------------------------------------------------------------------

describe('splitDiffByFile', () => {
  it('splits a multi-file diff into individual sections', () => {
    const diff = makeDiff(
      tsSection('src/foo.ts'),
      tsSection('src/bar.ts'),
      tsSection('src/baz.ts')
    );

    const sections = splitDiffByFile(diff);

    expect(sections).toHaveLength(3);
    expect(sections[0].filePath).toBe('src/foo.ts');
    expect(sections[1].filePath).toBe('src/bar.ts');
    expect(sections[2].filePath).toBe('src/baz.ts');
  });

  it('excludes filtered files from the split result', () => {
    const diff = makeDiff(
      tsSection('src/foo.ts'),
      lockSection(),
      tsSection('src/bar.ts')
    );

    const sections = splitDiffByFile(diff);

    expect(sections).toHaveLength(2);
    expect(sections.map(s => s.filePath)).toEqual(['src/foo.ts', 'src/bar.ts']);
  });

  it('includes the full diff content for each section', () => {
    const diff = tsSection('src/foo.ts');
    const sections = splitDiffByFile(diff);

    expect(sections).toHaveLength(1);
    expect(sections[0].diff).toContain('diff --git');
    expect(sections[0].diff).toContain("console.log('hello')");
  });

  it('returns empty array for diff with only non-reviewable files', () => {
    const diff = makeDiff(lockSection(), binarySection());
    const sections = splitDiffByFile(diff);

    expect(sections).toHaveLength(0);
  });

  it('returns empty array for empty diff', () => {
    const sections = splitDiffByFile('');
    expect(sections).toHaveLength(0);
  });

  it('sets isNewFile=true for new files (diff --git a/dev/null)', () => {
    const diff = newFileSection('src/auth.ts');
    const sections = splitDiffByFile(diff);

    expect(sections).toHaveLength(1);
    expect(sections[0].isNewFile).toBe(true);
    expect(sections[0].filePath).toBe('src/auth.ts');
  });

  it('sets isNewFile=false for existing file changes', () => {
    const diff = tsSection('src/foo.ts');
    const sections = splitDiffByFile(diff);

    expect(sections).toHaveLength(1);
    expect(sections[0].isNewFile).toBe(false);
  });

  it('correctly mixes new and existing files in split results', () => {
    const diff = makeDiff(
      newFileSection('src/auth.ts'),
      tsSection('src/foo.ts'),
      newFileSection('src/utils.ts'),
      tsSection('src/bar.ts')
    );
    const sections = splitDiffByFile(diff);

    expect(sections).toHaveLength(4);
    expect(sections[0].isNewFile).toBe(true);
    expect(sections[1].isNewFile).toBe(false);
    expect(sections[2].isNewFile).toBe(true);
    expect(sections[3].isNewFile).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// Tests — isNewFile
// ---------------------------------------------------------------------------

describe('isNewFile', () => {
  it('returns true for "new file mode" marker', () => {
    const section = `diff --git a/dev/null b/src/foo.ts
new file mode 100644
--- /dev/null
+++ b/src/foo.ts`;
    expect(isNewFile(section)).toBe(true);
  });

  it('returns true for "a/dev/null" in diff header', () => {
    const section = `diff --git a/dev/null b/src/bar.ts
index 0000000..e69de29
--- /dev/null
+++ b/src/bar.ts`;
    expect(isNewFile(section)).toBe(true);
  });

  it('returns false for existing file changes', () => {
    const section = `diff --git a/src/foo.ts b/src/foo.ts
--- a/src/foo.ts
+++ b/src/foo.ts`;
    expect(isNewFile(section)).toBe(false);
  });

  it('returns false for empty string', () => {
    expect(isNewFile('')).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// Tests — normalizeGitLabDiffResponse
// ---------------------------------------------------------------------------

describe('normalizeGitLabDiffResponse', () => {
  it('returns plain unified diff text unchanged (not JSON)', () => {
    const diff = tsSection('src/foo.ts');
    expect(normalizeGitLabDiffResponse(diff)).toBe(diff);
  });

  it('returns non-GitLab JSON unchanged', () => {
    const json = JSON.stringify({ foo: 'bar', baz: 42 });
    expect(normalizeGitLabDiffResponse(json)).toBe(json);
  });

  it('returns JSON array without "diff" fields unchanged', () => {
    const json = JSON.stringify([{ name: 'a' }, { name: 'b' }]);
    expect(normalizeGitLabDiffResponse(json)).toBe(json);
  });

  it('converts a single-file GitLab API array to unified diff', () => {
    const apiResponse = JSON.stringify([
      {
        old_path: 'src/foo.ts',
        new_path: 'src/foo.ts',
        diff: '@@ -1,3 +1,4 @@\n const x = 1;\n+console.log("hi");\n const y = 2;\n const z = 3;\n',
        new_file: false,
        deleted_file: false,
      },
    ]);
    const result = normalizeGitLabDiffResponse(apiResponse);
    expect(result).toContain('diff --git a/src/foo.ts b/src/foo.ts');
    expect(result).toContain('--- a/src/foo.ts');
    expect(result).toContain('+++ b/src/foo.ts');
    expect(result).toContain('@@ -1,3 +1,4 @@');
    expect(result).toContain('+console.log("hi");');
  });

  it('converts a multi-file GitLab API array to two diff sections', () => {
    const apiResponse = JSON.stringify([
      {
        old_path: 'src/foo.ts',
        new_path: 'src/foo.ts',
        diff: '@@ -1 +1 @@\n-old\n+new\n',
        new_file: false,
        deleted_file: false,
      },
      {
        old_path: 'src/bar.ts',
        new_path: 'src/bar.ts',
        diff: '@@ -5 +5 @@\n-x\n+y\n',
        new_file: false,
        deleted_file: false,
      },
    ]);
    const result = normalizeGitLabDiffResponse(apiResponse);
    expect(result).toContain('diff --git a/src/foo.ts b/src/foo.ts');
    expect(result).toContain('diff --git a/src/bar.ts b/src/bar.ts');
  });

  it('handles the {diffs:[...]} wrapper form', () => {
    const apiResponse = JSON.stringify({
      diffs: [
        {
          old_path: 'src/baz.ts',
          new_path: 'src/baz.ts',
          diff: '@@ -1 +1 @@\n-a\n+b\n',
          new_file: false,
          deleted_file: false,
        },
      ],
    });
    const result = normalizeGitLabDiffResponse(apiResponse);
    expect(result).toContain('diff --git a/src/baz.ts b/src/baz.ts');
    expect(result).toContain('@@ -1 +1 @@');
  });

  it('handles new_file: true with correct headers', () => {
    const apiResponse = JSON.stringify([
      {
        old_path: 'src/new.ts',
        new_path: 'src/new.ts',
        diff: '@@ -0,0 +1,2 @@\n+export const x = 1;\n+export const y = 2;\n',
        new_file: true,
        deleted_file: false,
      },
    ]);
    const result = normalizeGitLabDiffResponse(apiResponse);
    expect(result).toContain('diff --git a/dev/null b/src/new.ts');
    expect(result).toContain('new file mode 100644');
    expect(result).toContain('--- /dev/null');
    expect(result).toContain('+++ b/src/new.ts');
  });

  it('handles deleted_file: true with correct +++ header', () => {
    const apiResponse = JSON.stringify([
      {
        old_path: 'src/gone.ts',
        new_path: 'src/gone.ts',
        diff: '@@ -1,2 +0,0 @@\n-export const x = 1;\n-export const y = 2;\n',
        new_file: false,
        deleted_file: true,
      },
    ]);
    const result = normalizeGitLabDiffResponse(apiResponse);
    expect(result).toContain('diff --git a/src/gone.ts b/src/gone.ts');
    expect(result).toContain('+++ /dev/null');
  });

  it('integration: output feeds into splitDiffByFile correctly', () => {
    const apiResponse = JSON.stringify([
      {
        old_path: 'src/alpha.ts',
        new_path: 'src/alpha.ts',
        diff: '@@ -1,3 +1,4 @@\n const a = 1;\n+const b = 2;\n const c = 3;\n const d = 4;\n',
        new_file: false,
        deleted_file: false,
      },
      {
        old_path: 'src/beta.ts',
        new_path: 'src/beta.ts',
        diff: '@@ -10,3 +10,4 @@\n const x = 10;\n+const y = 11;\n const z = 12;\n',
        new_file: false,
        deleted_file: false,
      },
    ]);
    const unified = normalizeGitLabDiffResponse(apiResponse);
    const sections = splitDiffByFile(unified);
    expect(sections).toHaveLength(2);
    expect(sections[0].filePath).toBe('src/alpha.ts');
    expect(sections[1].filePath).toBe('src/beta.ts');
    expect(sections[0].isNewFile).toBe(false);
  });

  it('integration: new_file entry is detected by splitDiffByFile', () => {
    const apiResponse = JSON.stringify([
      {
        old_path: 'src/brand_new.ts',
        new_path: 'src/brand_new.ts',
        diff: '@@ -0,0 +1 @@\n+export const init = true;\n',
        new_file: true,
        deleted_file: false,
      },
    ]);
    const unified = normalizeGitLabDiffResponse(apiResponse);
    const sections = splitDiffByFile(unified);
    expect(sections).toHaveLength(1);
    expect(sections[0].isNewFile).toBe(true);
    expect(sections[0].filePath).toBe('src/brand_new.ts');
  });
});

// ---------------------------------------------------------------------------
// Tests — normalizeRemoteDiff
// ---------------------------------------------------------------------------

describe('normalizeRemoteDiff', () => {
  it('returns unified diff with headers unchanged', () => {
    const unified = `diff --git a/src/foo.ts b/src/foo.ts
--- a/src/foo.ts
+++ b/src/foo.ts
@@ -1 +1 @@
-const x = 1;
+const x = 2;`;
    expect(normalizeRemoteDiff(unified)).toBe(unified);
  });

  it('adds diff header to bare patch with +++ path', () => {
    const patch = `+++ b/src/bar.ts
@@ -1 +1 @@
-const a = 1;
+const a = 2;`;
    const result = normalizeRemoteDiff(patch);
    expect(result).toContain('diff --git a/src/bar.ts b/src/bar.ts');
    expect(result).toContain(patch);
  });

  it('returns bare hunk unchanged (cannot synthesize header without filename)', () => {
    // Without a +++ line, we cannot extract the filename to synthesize a header
    const patch = `@@ -5,3 +5,4 @@
 const x = 10;
+const y = 11;
 const z = 12;`;
    const result = normalizeRemoteDiff(patch);
    // Should return unchanged since we can't determine the file path
    expect(result).toBe(patch);
  });

  it('returns text unchanged if format not recognized', () => {
    const unknown = 'some random text without diff markers';
    expect(normalizeRemoteDiff(unknown)).toBe(unknown);
  });

  it('integration: normalized output feeds into splitDiffByFile', () => {
    const patch = `+++ b/src/integrate.ts
@@ -1 +1 @@
-old
+new`;
    const normalized = normalizeRemoteDiff(patch);
    const sections = splitDiffByFile(normalized);
    expect(sections).toHaveLength(1);
    expect(sections[0].filePath).toBe('src/integrate.ts');
  });
});
