// src/diffFilter.ts
// Pre-processes the raw git unified diff before it is sent to the AI.
//
// Goals:
//   1. Remove file sections that carry zero review value (lock files, binaries,
//      auto-generated code) — these can account for 30–80 % of the token payload
//      while contributing nothing to the review quality.
//   2. Keep every file section that is reviewable, completely intact (no line
//      trimming, no hunk truncation) so the AI still gets accurate line numbers.
//   3. Report what was stripped so the user can verify the filter is sane.

// ─────────────────────────────────────────────────────────────────────────────
// Filter rules
// ─────────────────────────────────────────────────────────────────────────────

/**
 * File-name patterns that are never worth reviewing.
 * Each entry is tested against the full path that appears in the diff header,
 * e.g. "b/package-lock.json" or "b/src/generated/proto/foo.pb.h".
 */
const SKIP_FILENAME_PATTERNS: RegExp[] = [
  // Dependency lock files
  /package-lock\.json$/i,
  /yarn\.lock$/i,
  /pnpm-lock\.yaml$/i,
  /Cargo\.lock$/i,
  /Gemfile\.lock$/i,
  /composer\.lock$/i,
  /poetry\.lock$/i,
  /Pipfile\.lock$/i,
  /go\.sum$/i,
  /flake\.lock$/i,
  /\.lock$/i,

  // Build artefacts & compiled outputs
  /\.min\.(js|css)$/i,
  /\.bundle\.js$/i,
  /\.chunk\.js$/i,
  /dist\//i,
  /build\//i,
  /out\//i,
  /\.map$/i,           // source maps

  // Auto-generated code
  /\.pb\.h$/i,         // protobuf C headers
  /\.pb\.cc$/i,
  /\.pb\.go$/i,
  /\.pb\.py$/i,
  /\.pb\.js$/i,
  /\.pb\.ts$/i,
  /\.generated\./i,
  /generated\//i,
  /_pb2\.py$/i,
  /\.g\.dart$/i,
  /\.freezed\.dart$/i,
  /\.gr\.dart$/i,

  // IDE / OS noise
  /\.DS_Store$/i,
  /Thumbs\.db$/i,
  /\.suo$/i,
  /\.user$/i,

  // Coverage & test reports
  /coverage\//i,
  /lcov\.info$/i,
  /\.coverage$/i,

  // Changelog / migration autogenerated
  /CHANGELOG\.md$/i,
];

/**
 * Patterns matched against the *content* of the diff section header line
 * (the `diff --git` line). A match means the entire file section is dropped.
 */
const SKIP_BINARY_PATTERN = /^Binary files .* differ/m;

// ─────────────────────────────────────────────────────────────────────────────
// Split helpers
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Splits a unified diff into per-file sections.
 * Each section starts with "diff --git a/… b/…" and includes everything up to
 * (but not including) the next such header, or the end of the string.
 */
function splitDiffIntoFileSections(diff: string): string[] {
  // Split on lines that start with "diff --git"
  const sections: string[] = [];
  const lines = diff.split('\n');
  let current: string[] = [];

  for (const line of lines) {
    if (line.startsWith('diff --git ') && current.length > 0) {
      sections.push(current.join('\n'));
      current = [];
    }
    current.push(line);
  }
  if (current.length > 0) {
    sections.push(current.join('\n'));
  }
  return sections;
}

/**
 * Extracts the "b/" path from a diff section header, e.g.
 *   "diff --git a/src/foo.c b/src/foo.c"  →  "src/foo.c"
 * Returns the raw header line if the pattern doesn't match.
 */
function extractFilePath(section: string): string {
  const m = section.match(/^diff --git a\/.+ b\/(.+)/m);
  return m ? m[1].trim() : section.split('\n')[0];
}

/**
 * Detects whether a diff section represents a brand-new file
 * (not previously tracked, i.e. added with no prior version).
 *
 * Git represents new files in the diff in two ways:
 *   1. `diff --git a/dev/null b/src/foo.ts`  (a side is /dev/null)
 *   2. `new file mode 100644` in the header
 *   3. `+++ /dev/null` for deletions (not relevant here)
 */
export function isNewFile(section: string): boolean {
  if (section.includes('new file mode')) { return true; }
  // a/dev/null means the file did not exist before → brand new
  if (/^diff --git a\/dev\/null /m.test(section)) { return true; }
  return false;
}

/**
 * Returns true when the section represents a file that should be skipped.
 */
function shouldSkipSection(section: string, filePath: string): boolean {
  // Binary file marker anywhere in the section
  if (SKIP_BINARY_PATTERN.test(section)) {
    return true;
  }
  // Filename-based rules
  for (const pattern of SKIP_FILENAME_PATTERNS) {
    if (pattern.test(filePath)) {
      return true;
    }
  }
  return false;
}

// ─────────────────────────────────────────────────────────────────────────────
// Public API
// ─────────────────────────────────────────────────────────────────────────────

export interface DiffFilterResult {
  /** The filtered diff — ready to pass to the AI. */
  filteredDiff: string;
  /** Number of file sections kept. */
  keptFiles: number;
  /** Number of file sections removed. */
  skippedFiles: number;
  /** Names of the files that were removed. */
  skippedFilePaths: string[];
  /** Names of the files that were kept. */
  keptFilePaths: string[];
  /** Rough token savings estimate (4 chars ≈ 1 token). */
  estimatedTokensSaved: number;
}

/**
 * Filters a raw unified git diff, removing file sections that have no review
 * value. The returned `filteredDiff` is safe to pass directly to the AI prompt.
 */
export function filterDiff(rawDiff: string): DiffFilterResult {
  const sections = splitDiffIntoFileSections(rawDiff);
  const kept: string[] = [];
  const skippedFilePaths: string[] = [];
  const keptFilePaths: string[] = [];
  let charsRemoved = 0;

  for (const section of sections) {
    const filePath = extractFilePath(section);
    if (shouldSkipSection(section, filePath)) {
      skippedFilePaths.push(filePath);
      charsRemoved += section.length;
    } else {
      kept.push(section);
      keptFilePaths.push(filePath);
    }
  }

  return {
    filteredDiff: kept.join('\n'),
    keptFiles: kept.length,
    skippedFiles: skippedFilePaths.length,
    skippedFilePaths,
    keptFilePaths,
    estimatedTokensSaved: Math.round(charsRemoved / 4),
  };
}

/**
 * Splits a unified diff into individual per-file sections.
 * Used by P3 (per-file parallel review) to fan out one AI call per file.
 * Applies the same filter rules — noisy files are excluded before splitting.
 */
export function splitDiffByFile(rawDiff: string): Array<{ filePath: string; diff: string; isNewFile: boolean }> {
  const sections = splitDiffIntoFileSections(rawDiff);
  const result: Array<{ filePath: string; diff: string; isNewFile: boolean }> = [];

  for (const section of sections) {
    const filePath = extractFilePath(section);
    if (!shouldSkipSection(section, filePath)) {
      // Only include sections that actually have changed lines (+ or -)
      if (/^[+-]/m.test(section)) {
        result.push({ filePath, diff: section, isNewFile: isNewFile(section) });
      }
    }
  }

  return result;
}

// ─────────────────────────────────────────────────────────────────────────────
// GitLab API diff normalizer
// ─────────────────────────────────────────────────────────────────────────────

/**
 * If `text` is a GitLab REST API diff response (a JSON array of diff objects,
 * or a `{diffs:[...]}` wrapper), converts it to standard unified diff format.
 *
 * The GitLab API returns per-file diff content as a JSON string value where
 * newlines are encoded as `\n` escape sequences.  `JSON.parse()` converts
 * those escape sequences to real newlines so that `@@` hunk headers appear
 * at the start of a line and `extractDiffContext` can build its `lineMap`.
 *
 * Returns `text` unchanged if JSON parsing fails or the parsed value does not
 * look like a GitLab diff response.
 */
export function normalizeGitLabDiffResponse(text: string): string {
  let parsed: any;
  try { parsed = JSON.parse(text); } catch { return text; }

  // Accept both a bare array and a {diffs:[...]} wrapper
  const items: any[] = Array.isArray(parsed)
    ? parsed
    : Array.isArray(parsed?.diffs) ? parsed.diffs : [];

  // Must have at least one object with a string `diff` field to be recognised
  if (items.length === 0 || typeof items[0]?.diff !== 'string') { return text; }

  const sections: string[] = [];
  for (const item of items) {
    const newPath     = typeof item.new_path === 'string' ? item.new_path : '';
    const oldPath     = typeof item.old_path === 'string' ? item.old_path : newPath;
    const diffContent = typeof item.diff    === 'string' ? item.diff     : '';
    if (!newPath && !diffContent) { continue; }

    const isNew     = !!item.new_file;
    const isDeleted = !!item.deleted_file;

    // Build a standard unified-diff header so downstream helpers recognise it
    const gitHeader = isNew
      ? `diff --git a/dev/null b/${newPath}\nnew file mode 100644`
      : `diff --git a/${oldPath} b/${newPath}`;
    const aLine = isNew     ? '--- /dev/null'  : `--- a/${oldPath}`;
    const bLine = isDeleted ? '+++ /dev/null'  : `+++ b/${newPath}`;

    sections.push(`${gitHeader}\n${aLine}\n${bLine}\n${diffContent}`);
  }

  return sections.length > 0 ? sections.join('\n') : text;
}

// ─────────────────────────────────────────────────────────────────────────────
// Remote diff normalizer (MCP format → unified diff)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Normalize diffs from various MCP servers into standard unified-diff format.
 * - GitHub MCP: returns unified diffs with `diff --git` headers — passes through.
 * - GitHub get_pull_request_files variant: returns patch strings per-file,
 *   missing the `diff --git` header. Prepends it.
 * - GitLab MCP: may return JSON objects or `diff --git`-less patches; normalize.
 */
export function normalizeRemoteDiff(raw: string): string {
  // Already in unified format with headers — pass through.
  if (raw.includes('diff --git ')) { return raw; }

  // If it's a bare patch (starts with "--- a/" or "@@" or "+++"), synthesize a header.
  if (/^(---|\+\+\+|@@)/m.test(raw)) {
    // Best-effort: extract file paths from "+++ b/..." line
    const pathMatch = raw.match(/^\+\+\+ b\/(.+)$/m);
    if (pathMatch) {
      const filePath = pathMatch[1].trim();
      return `diff --git a/${filePath} b/${filePath}\n${raw}`;
    }
    // Try to extract from "@@ -X,Y +Z,W @@" pattern as fallback
    const hunkMatch = raw.match(/^@@ -\d+(?:,\d+)? \+\d+(?:,\d+)? @@\s*(?:^---|\+\+\+)/m);
    if (hunkMatch) {
      const fileLine = raw.split('\n').find(l => l.startsWith('+++ b/'));
      if (fileLine) {
        const fp = fileLine.slice(4).trim();
        return `diff --git a/${fp} b/${fp}\n${raw}`;
      }
    }
  }

  // Unknown format — return as-is; splitter will fall back to treating
  // the whole thing as one file section.
  return raw;
}
